name: Check for common errors after updating Makefile.venv
on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Python unittest framework
        run: |
          python3 -m unittest
